image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_JOB_USER -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - develop

test:
  stage: test
  script:
    - docker pull $IMAGE_TAG
    - docker run $IMAGE_TAG python --version
    - docker run $IMAGE_TAG python manage.py test
    - docker run $IMAGE_TAG cd self_blog/static/self_blog && yarn lint
  only:
    - develop

release_dev:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop
