version: '3'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: baohuynh
      POSTGRES_DB: self_blog
      PGDATA: /var/lib/postgres
    volumes:
    - db:/var/lib/postgres

volumes:
  db: