version: '3'

services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
      PGDATA: /var/lib/postgres
    env_file:
      - .env
    volumes:
    - db:/var/lib/postgres

volumes:
  db: